name: Release
on: 
  push:
    branches:
      - prod
jobs:
  deploy:
    environment: Production
    runs-on:
      labels: [self-hosted, foisor]
    steps:
      - run: echo $(pwd)
      - run: echo "caca"
      - run: node --version
      - run: echo $USER
      - run: nvm use 22
      - run: node --version
