name: Production
on: 
  push:
    branches:
      - main
jobs:
  deploy:
    environment: staging_environment
    runs-on:
      labels: [self-hosted, foisor]
    steps:
      - run: echo $(pwd)
      - run: echo "caca"
      - run: node --version
